[package]
name = "revolt"
version = "0.2.9"
authors = ["Paul Makles <paulmakles@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb = { version = "1.1.0", default-features = false, features = ["sync"] } # FIXME: rewrite database with async API
rocket = { version = "0.4.5", default-features = false }
once_cell = "1.4.1"
dotenv = "0.15.0"
ulid = "0.4.0"
serde = { version = "1.0.115", features = ["derive"] }
rocket_contrib = "0.4.5"
validator = "0.10.1"
bcrypt = "0.8.2"
chrono = "0.4.15"
rand = "0.7.3"
time = "0.2.16"
reqwest = { version = "0.10.8", features = ["blocking", "json"] }
num_enum = "0.5.1"
ws = "0.9.1"
hashbrown = "0.8.2"
serde_json = "1.0.57"
rocket_cors = "0.5.2"
bitfield = "0.13.2"
lru = "0.6.0"
lazy_static = "1.4.0"
log = "0.4.11"
env_logger = "0.7.1"
