[package]
name = "revolt"
# To help optimise CI and Docker builds.
# Version here is left as 0.0.0, please
# adjust and run ./set_version.sh instead.
version = "0.0.0"
authors = ["Paul Makles <paulmakles@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# Utility
url = "2.2.2"
log = "0.4.14"
dotenv = "0.15.0"
linkify = "0.7.0"
once_cell = "1.8.0"
env_logger = "0.9.0"
lazy_static = "1.4.0"
ctrlc = { version = "3.2.0", features = ["termination"] }

# Lang. Utilities
regex = "1"
num_enum = "0.5.4"
impl_ops = "0.1.1"
bitfield = "0.13.2"
phf = { version = "0.10.0", features = ["macros"] }

# ID / key generation
ulid = "0.4.1"
nanoid = "0.4.0"
base64 = "0.13.0"

# serde
serde_json = "1.0.67"
serde = { version = "1.0.130", features = ["derive"] }
validator = { version = "0.14.0", features = ["derive"] }
rmp-serde = "0.15.5"

# async
futures = "0.3.17"
chrono = "0.4.19"
reqwest = { version = "0.11.4", features = ["json"] }
async-std = { version = "1.10.0", features = ["tokio1", "tokio02", "attributes"] }

# internal util
web-push = "0.7.2"
many-to-many = "0.1.7"
lettre = "0.10.0-rc.3"
rauth = { git = "https://github.com/insertish/rauth", rev = "ad2f5ad1657f4b20c8e483cc1d6c513ff9b22ae1" }
hive_pubsub = { git = "https://gitlab.insrt.uk/insert/hive", rev = "a89826df2b30166220e68a6ed01a58b751456604", features = ["mongo"] }

# web
rocket-governor = { version = "0.0.1-rc.9", features = ["logger"] }
async-tungstenite = { version = "0.15.0", features = ["async-std-runtime"] }
rocket = { version = "0.5.0-rc.1", default-features = false, features = ["json"] }
mongodb = { version = "1.2.3", features = ["tokio-runtime"], default-features = false }
rocket_cors = { git = "https://github.com/lawliet89/rocket_cors", rev = "5843861a88958c16bfaa0b40f0d8910772bcd2f6" }
