[package]
name = "revolt"
version = "0.1.0"
authors = ["Paul Makles <paulmakles@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb = "0.9.0"
bson = "0.14.0"
rocket = { version = "0.4.2", default-features = false }
once_cell = "1.3.1"
dotenv = "0.15.0"
ulid = "0.3.1"
serde = { version = "1.0", features = ["derive"] }
rocket_contrib = "0.4.2"
lettre = "0.9.2"
lettre_email = "0.9.2"
sendmail = "2.0.0"
