[package]
name = "revolt"
version = "0.2.3"
authors = ["Paul Makles <paulmakles@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb = { version = "1.1.0-beta", default-features = false, features = ["sync"] } # FIXME: rewrite database with async API
rocket = { version = "0.4.4", default-features = false }
once_cell = "1.3.1"
dotenv = "0.15.0"
ulid = "0.3.1"
serde = { version = "1.0", features = ["derive"] }
rocket_contrib = "0.4.4"
validator = "0.10.0"
bcrypt = "0.7.0"
chrono = "0.4.11"
rand = "0.7.3"
time = "0.2.9"
reqwest = { version = "0.10.4", features = ["blocking", "json"] }
num_enum = "0.4.3"
ws = "0.9.1"
hashbrown = "0.7.1"
serde_json = "1.0.51"
rocket_cors = "0.5.2"
bitfield = "0.13.2"
lru = "0.5.3"
lazy_static = "1.4.0"
