[package]
name = "revolt"
version = "0.1.0"
authors = ["Paul Makles <paulmakles@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mongodb = "0.9.0"
bson = "0.14.0"
rocket = { version = "0.4.2", default-features = false }
once_cell = "1.3.1"
dotenv = "0.15.0"
ulid = "0.3.1"
serde = { version = "1.0", features = ["derive"] }
rocket_contrib = "0.4.2"
validator = "0.10.0"
bcrypt = "0.6.1"
chrono = "0.4.10"
rand = "0.7.3"
time = "0.2.4"
reqwest = { version = "0.10.1", features = ["blocking", "json"] }
num_enum = "0.4.2"
ws = "0.9.1"
hashbrown = "0.7.0"
serde_json = "1.0.47"
rocket_cors = "0.5.1"
