disallowed-methods = [
    # Shouldn't need to access these directly
    "revolt_database::models::bots::model::Bot::remove_field",

    # Prefer to use Object::update()
    "revolt_database::models::bots::ops::AbstractBots::update_bot",
    "revolt_database::models::safety_strikes::ops::AbstractAccountStrikes::update_account_strike",

    # Prefer to use Object::delete()
    "revolt_database::models::bots::ops::AbstractBots::delete_bot",
    "revolt_database::models::safety_strikes::ops::AbstractAccountStrikes::delete_account_strike",
]
