disallowed-methods = [
    # Shouldn't need to access these directly
    "revolt_database::models::bots::model::Bot::remove_field",

    # Prefer to use Object::create()
    "revolt_database::models::bots::ops::AbstractBots::*",
    "revolt_database::models::bots::ops::AbstractBots::insert_bot",
    "revolt_database::models::bots::ops::AbstractChannelInvites::insert_invite",
    "revolt_database::models::bots::ops::AbstractChannelUnreads::acknowledge_message",
    "revolt_database::models::bots::ops::AbstractChannels::insert_channel",
    "revolt_database::models::bots::ops::AbstractEmojis::insert_emoji",
    "revolt_database::models::bots::ops::AbstractMessages::insert_message",
    "revolt_database::models::bots::ops::AbstractRatelimitEvents::insert_ratelimit_event",
    "revolt_database::models::bots::ops::AbstractRatelimitEvents::insert_ratelimit_event",
    "revolt_database::models::bots::ops::AbstractServerBans::insert_ban",
    "revolt_database::models::bots::ops::AbstractServerMembers::insert_member",
    "revolt_database::models::bots::ops::AbstractServers::insert_server",
    "revolt_database::models::bots::ops::AbstractUsers::insert_user",

    # Prefer to use Object::update(&self)
    "revolt_database::models::bots::ops::AbstractBots::update_bot",

    # Prefer to use Object::delete(&self)
    "revolt_database::models::bots::ops::AbstractBots::delete_bot",
]
