version: '2'

services:
  database:
    image: mongo
    restart: always
  web:
    build: .
    environment:
      - REVOLT_MONGO_URI=mongodb://localhost
      - REVOLT_PUBLIC_URL=https://local.revolt.chat
      - REVOLT_USE_EMAIL_VERIFICATION=0
      - REVOLT_UNSAFE_NO_EMAIL=1
      - REVOLT_UNSAFE_NO_CAPTCHA=1
    ports:
      - "8000:8000"
      - "9000:9000"
    restart: unless-stopped
