[package]
name = "revolt-models"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
serde = [ "dep:serde" ]
schemas = [ "dep:schemars" ]
from_database = [ "revolt-database" ]

default = [ "serde", "from_database" ]

[dependencies]
# Repo
revolt-database = { path = "../database", optional = true }

# Serialisation
serde = { version = "1", features = ["derive"], optional = true }

# Spec Generation
schemars = { version = "0.8.8", optional = true }
