[package]
name = "revolt-database"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# Databases
mongodb = [ "dep:mongodb" ]

# ... Other
async-std-runtime = [ "async-std" ]

# Default Features
default = [ "mongodb", "async-std-runtime" ]

[dependencies]
# Utility
log = "*"
nanoid = "0.4.0"

# Serialisation
serde_json = "1"
serde = { version = "1", features = ["derive"] }
optional_struct = { git = "https://github.com/insertish/OptionalStruct", rev = "ee56427cee1f007839825d93d07fffd5a5e038c7" }

# Database
mongodb = { optional = true, version = "2.1.0", default-features = false }

# Async Language Features
futures = "0.3.19"
async-trait = "0.1.51"
async-recursion = "1.0.4"

# Async
async-std = { version = "1.8.0", features = ["attributes"], optional = true }

# Authifier
authifier = { version = "1.0", default-features = false }
